---
- name: deploy and configure nginx oss webserver
  hosts: webservers
  remote_user: ubuntu
  become: true
  roles:
    - ansible-role-nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        server_name: localhost
        listen:
          listen_localhost:
            ip: 0.0.0.0
            port: 80
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: demo_index.html
              autoindex: false
          http_demo_conf: true