---
# # for some reason this does not work with the Jinja template
- hosts: localhost

  tasks:
  - name: read webservers file
    shell: cat {{playbook_dir}}/webservers
    register: webservers

  - name: output
    debug:
      var: webservers


- hosts: loadbalancers
  remote_user: ubuntu
  become: true

  pre_tasks:
  - name: load the vars
    include_vars: 
      file: "{{playbook_dir}}/nginx_lb_plus_vars.yaml"

  - name: replace webserverUno in dynamic configuration
    set_fact:
      nginx_http_template: "{{ nginx_http_template|combine({'default': {'upstreams': {'upstream_1': {'servers': {'backend_server_1': {'address': hostvars['localhost']['webservers'].stdout_lines[1]}}}}}}, recursive=True) }}"

  - name: replace webserverDos in dynamic configuration
    set_fact:
      nginx_http_template: "{{ nginx_http_template|combine({'default': {'upstreams': {'upstream_1': {'servers': {'backend_server_2': {'address': hostvars['localhost']['webservers'].stdout_lines[2]}}}}}}, recursive=True) }}"

  - name: output the config
    debug:
      var: nginx_http_template

  roles:
    - ansible-role-nginx

  # post_tasks:
  # - name: restart nginx
  #   service:
  #     name=nginx
  #     state=restarted
