---
# # for some reason this does not work with the Jinja template

- hosts: loadbalancers, webservers
  remote_user: ubuntu
  become: true

  tasks:
  - name: stop nginx
    service:
        name: nginx
        state: stopped

  - name: ensure nginx is not installed
    apt: 
      name: nginx 
      state: absent

  - name: clean and update
    apt:
      autoclean: yes
      autoremove: yes
      update_cache: yes

